spring:
  application:
    name: backend-test-java

  datasource:
    url: jdbc:mysql://mysql_backend_test_java:3306/backend-test-java
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: INFO
    com.meudroz.backend_test_java: DEBUG

